import { Spinner } from "std-widgets.slint";
import { StateLayer } from "state_layer.slint";
import { Token } from "../global.slint";

export component LoadingButton inherits Rectangle {
    in property <color> on-surface: Token.color.on-surface;
    in property <color> surface: Token.color.surface;
    in-out property <bool> is-loading: false;
    in property <string> content: "No Content";
    in property <length> font-size: Token.font.body.large.size;
    // callback clicked <=> area.clicked;
    clip: true;
    private property <length> max-radius: 20px;
    private property <length> icon-size: 18px;
    private property <length> default-padding: 24px;
    private property <length> icon-padding: 16px;
    private property <length> default-spacing: 8px;
    border-radius: self.height / 2 > max-radius ? max-radius : self.height / 2;
    height: 40px;
    StateLayer {
        background: on-surface;
        is-hover: area.has-hover;
        is-press: area.pressed;
    }

    _spinner := Spinner {
        x: icon-padding;
        height: icon-size;
        width: icon-size;
        indeterminate: true;
    }

    _text := Text {
        x: (root.width - self.width) / 2;
        text: content;
        font-size: font-size;
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    area := TouchArea {
        clicked => {
            is-loading = !is-loading;
        }
    }

    states [
        loading when is-loading: {
        // width = icon-padding + icon-size + default-spacing + _text.width + default-padding
            width: icon-padding + icon-size + default-spacing + _text.width + default-padding;
            _text.x: icon-padding + icon-size + default-spacing;
            _spinner.opacity: 1;
            in {
                animate width, _text.x, _spinner.opacity {
                    duration: 200ms;
                    easing: ease-in-out-quint;
                }
            }
            out {
                animate width, _text.x, _spinner.opacity {
                    duration: 200ms;
                    easing: ease-in-out-quint;
                }
            }
        }
        normal when !is-loading: {
        // width = default-padding + _text.width + default-padding
            width: default-padding + _text.width + default-padding;
            _text.x: default-padding;
            _spinner.opacity: 0;
        }
    ]
}
