import { AboutSlint } from "std-widgets.slint";
import { SText , SIcon} from "../modules/surrealism-ui/index.slint";
export component HelloComponent {
  Rectangle {
    layout := VerticalLayout {
      spacing: 16px;
      padding: 16px;
      AboutSlint {
        height: 160px;
      }
      SText {
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 42px;
        font-weight: 700;
        color: #2379F4;
        text: "Slint + SurrealismUI + Rust";
      }
      HorizontalLayout {
        alignment: center;
        SIcon {
          height: 60px;
          width: 60px;
          colorize: #9401FD;
          source: @image-url("../assets/surrealism.svg");
        }
        SText {
          font-size: 60px;
          font-weight: 700;
          color: #ffffff;
          text: "urreal";
        }
        SText{
          font-size: 60px;
          font-weight: 700;
          color: #9401FD;
          text: "ism";
        }
      }
    }
  }
}