import { Palette, Button } from "std-widgets.slint";
import { MdStyleToken } from "../../logic/md_style_token.slint";

struct ImgPair {
    light: image,
    dark: image,
}

// icon won't change according to 
struct EventoIconCollection {
    evento: image,
    sast-link: image,
    arrow-left: image,
    card: image,
    category: image,
    department: image,
    history: image,
    home: image,
    info: image,
    error: image,
    locate: image,
    logout: image,
    me: image,
    schedule: image,
    setting: image,
    star-empty: image,
    star-full: image,
    tag: image,
    time: image,
    topic: image,
    tree-list: image,
    account-box: image,
    pentagon: image,
    check-circle: image,
}

struct EventoDisplayCollection {
    evento: image,
    evento-bg: image,
    avatar: image,
}

struct EventoImageCollection {
    icon: EventoIconCollection,
    display: EventoDisplayCollection,
}

export global EventoImageToken {
    out property <EventoImageCollection> image:{
        icon: icon,
        display: display,
    };
    pure function switcher(img: ImgPair) -> image {
        return MdStyleToken.is-darkmode ? img.dark : img.light;
    }
    //
    // icon used as small image in button, navbar and so on
    // icon will change according to darkmode switch
    property <EventoIconCollection> icon:{
        // exception for colorize
        evento: switcher({
            light: @image-url("./icon/evento.png"),
            dark: @image-url("./icon/evento_dark.png"),
        }),
        // sast-link is intended to be used in invert color
        sast-link: @image-url("./icon/sast-link.svg"),
        arrow-left: @image-url("./icon/arrow-left.svg"),
        card: @image-url("./icon/card.svg"),
        category: @image-url("./icon/category.svg"),
        department: @image-url("./icon/department.svg"),
        history: @image-url("./icon/history.svg"),
        home: @image-url("./icon/home.svg"),
        info: @image-url("./icon/info.svg"),
        error:@image-url("./icon/error.svg"),
        locate: @image-url("./icon/locate.svg"),
        logout: @image-url("./icon/logout.svg"),
        me: @image-url("./icon/me.svg"),
        schedule: @image-url("./icon/schedule.svg"),
        setting: @image-url("./icon/setting.svg"),
        star-empty: @image-url("./icon/star-empty.svg"),
        star-full: @image-url("./icon/star-full.svg"),
        tag: @image-url("./icon/tag.svg"),
        time: @image-url("./icon/time.svg"),
        topic: @image-url("./icon/topic.svg"),
        tree-list: @image-url("./icon/tree-list.svg"),
        account-box: @image-url("./icon/account-box-outline.svg"),
        pentagon: @image-url("./icon/pentagon.svg"),
        check-circle: @image-url("./icon/check-circle.svg"),
    };
    // display used as images bigger than icon
    // most display image won't change according to darkmode switch
    property <EventoDisplayCollection> display:{
        evento: switcher({
            light: @image-url("./display/evento/evento.png"),
            dark: @image-url("./display/evento/evento_dark.png"),
        }),
        evento-bg: @image-url("./display/evento/evento_bg.png"),
        avatar: @image-url("./display/avatar/avatar_1.svg"),
    };
}
