import { Token } from "../../global.slint";
import { Page, Empty } from "../../components/index.slint";

export global AboutPageBridge { }

export component AboutPage inherits Page {
    // TODO: implement About
    // optional
    background := Empty { }

    layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        placeholder := Rectangle {
            border-width: 4px;
            border-color: red;
            Text {
                text: "关于页面\n  ";
            }
        }
    }
}
