import { Token } from "../../global.slint";
import { Page, Empty } from "../../components/index.slint";
import { EventCardGroup } from "../../components/event_card.slint";

export global DiscoveryPageBridge { }

export component DiscoveryPage inherits Page {
    /*  demo code for generating corresponding C++ code correctly
        remove this when EventCard&EventCardGroup is truly used
        otherwise "Convert.h/Convert.cc" will fail to compile    */
    EventCardGroup {
        model: [
            {
                id: 1,
                summary-abbr: "软",
                summary: "软件研发部 C++组授课",
                time: "09.30 14:30 - 09.30 15:30",
                location: "仙林校区 大学生活动中心101",
                description: "组内授课"
            },
            {
                id: 2,
                summary-abbr: "软",
                summary: "软件研发部 Web组授课",
                time: "09.30 14:30 - 09.30 15:30",
                location: "仙林校区 大学生活动中心101",
                description: "组内授课"
            },
            {
                id: 3,
                summary-abbr: "软",
                summary: "软件研发部 C#组授课",
                time: "09.30 14:30 - 09.30 15:30",
                location: "仙林校区 大学生活动中心101",
                description: "组内授课"
            }
        ];
        item-clicked(event-struct) => {
            debug("id: " + event-struct.id + " title: " + event-struct.summary);
        }
    }

    // TODO: implement Discovery
    // optional
    background := Empty { }

    layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        placeholder := Rectangle {
            border-width: 4px;
            border-color: red;
            Text {
                text: "活动广场（用于发现活动）\n  进行中、未开始\n  （需要跳转到历史活动页面，需要多考虑一下）";
            }
        }
    }
}
