import { Token } from "../../global.slint";
import { Page, Empty } from "../../components/index.slint";

export global DiscoveryPageBridge { }

export component DiscoveryPage inherits Page {
    // TODO: implement Discovery
    // optional
    background := Empty { }

    layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        placeholder := Rectangle {
            border-width: 4px;
            border-color: red;
            Text {
                text: "活动广场（用于发现活动）\n  进行中、未开始\n  （需要跳转到历史活动页面，需要多考虑一下）";
            }
        }
    }
}
