import { Token } from "../../global.slint";
import { Page, Button, ButtonType } from "../../components/index.slint";
import { SCard,STimeLine,STimeLineItem } from "../../modules/surrealism-ui/index.slint";
import {SStar,SButton} from "../../modules/surrealism-ui/index.slint";
import { Card } from "../../components/card.slint";
import { SPagination } from "../../modules/surrealism-ui/index.slint";
import {Themes,UseIcons} from "../../modules/surrealism-ui/use/index.slint";
import { ScrollView, LineEdit } from "std-widgets.slint";
export global HistoryPageBridge { }

component CommentItem {
    property <string> context;
    property <bool> reviewed;
    property <bool> editing;
    VerticalLayout {
        spacing: 8px;
        SStar {
            score: 3;
            theme: Dark;
        }

        HorizontalLayout {
            spacing: 8px;
            LineEdit {
                width: 80%;
                height: 40px;
            }

            Button {
                content: "评价";
                type: ButtonType.filled-tonal;
                clicked => {
                    // TODO: implement review
                }
            }
        }
    }
}

component DividerVirtical inherits Rectangle {
    width: 8px;
    height: 100%;
    Rectangle {
        x: 2px;
        width: 4px;
        height: 90%;
        border-radius: 2px;
        background: Token.color.primary-container;
        Rectangle {
            y: parent.height / 2 - 4px;
            width: 8px;
            height: 8px;
            border-radius: 4px;
            background: Token.color.on-primary-container;
        }
    }
}

component HistoryCard inherits Rectangle {
    height: 100px;
    in property <string> date-time;
    in property <string> title;
    in property <string> department;
    in property <string> description;
    HorizontalLayout {
        spacing: 5px;
        Rectangle {
            Text {
                text: date-time;
                font-size: Token.font.body.large.size;
                font-weight: Token.font.body.large.weight;
                color: Token.color.outline;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }

        DividerVirtical { }

        Card {
            height: root.height;
            width: 90%;
            clicked() => {
            }
            HorizontalLayout {
                padding: 5px;
                spacing: 8px;
                VerticalLayout {
                    Text {
                        horizontal-alignment: TextHorizontalAlignment.left;
                        vertical-alignment: TextVerticalAlignment.top;
                        text: title;
                        overflow: elide;
                        font-size: Token.font.headline.small.size;
                        font-weight: Token.font.headline.small.weight;
                        color: Token.color.on-surface;
                    }

                    Text {
                        font-size: Token.font.label.large.size;
                        text: description;
                        overflow: elide;
                        color: Token.color.on-surface;
                    }
                }

                CommentItem {
                    width: 40%;
                }
            }
        }
    }
}

export component HistoryPage inherits Page {
    ScrollView {
        VerticalLayout {
            padding: 50px;
            spacing: 15px;
            Text {
                text: "历史活动";
                font-size: Token.font.headline.medium.size;
                font-weight: Token.font.headline.medium.weight;
                color: Token.color.outline;
            }

            VerticalLayout {
                spacing: 5px;
                HistoryCard {
                    date-time: "2024.7.24";
                    title: "软件研发部C++组授课";
                    description: "软件研发部C++组授课";
                }

                HistoryCard {
                    date-time: "2024.7.24";
                    title: "软件研发部C++组授课";
                    description: "软件研发部C++组授课";
                }

                HistoryCard {
                    date-time: "2024.7.24";
                    title: "软件研发部C++组授课";
                    description: "软件研发部C++组授课";
                }

                HistoryCard {
                    date-time: "2024.7.24";
                    title: "软件研发部C++组授课";
                    description: "软件研发部C++组授课";
                }
            }

            SPagination {
                page-size: 10;
                total: 100;
                visible-range: 6;
            }
        }
    }
}
