import { Token } from "../../global.slint";
import { Page, Empty } from "../../components/index.slint";

export global SearchPageBridge { }

export component SearchPage inherits Page {
    // TODO: implement Search
    // optional
    background := Empty { }

    layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        placeholder := Rectangle {
            border-width: 4px;
            border-color: red;
            Text {
                text: "搜索(部门活动)\n  按组筛选、按照自己参加筛选\n  对组添加订阅";
            }
        }
    }
}
