import { Token } from "../../global.slint";
import { Page, EventCardGroup, EventStruct } from "../../components/index.slint";
import { Button, LineEdit, ScrollView, ListView, StandardListView } from "std-widgets.slint";
import { StateLayer } from "../../components/state_layer.slint";

export global SearchPageBridge {
    out property <[StandardListViewItem]> department: [
        { text: "C++组"},   
        { text: "C#组"},   
        { text: "游戏组"},       
        { text: "Web组"},   
        { text: "Graphics组"},   
        { text: "运维组"},       
    ];
    out property <[EventStruct]> event-model: [
        {
            id: 1,
            summary-abbr: "软",
            summary: "软件研发部 C++组授课",
            time: "09.30 14:30 - 09.30 15:30",
            location: "仙林校区 大学生活动中心101",
            description: "组内授课"
        },
        {
            id: 2,
            summary-abbr: "软",
            summary: "软件研发部 Web组授课",
            time: "09.30 14:30 - 09.30 15:30",
            location: "仙林校区 大学生活动中心101",
            description: "组内授课"
        },
        {
            id: 3,
            summary-abbr: "软",
            summary: "软件研发部 C#组授课",
            time: "09.30 14:30 - 09.30 15:30",
            location: "仙林校区 大学生活动中心101",
            description: "组内授课"
        }
    ];
    callback filter-department(string);
    callback load-department-events(int);
}

export component SearchPage inherits Page {
    HorizontalLayout {
        padding: 50px;
        spacing: 20px;
        VerticalLayout {
            horizontal-stretch: 0.2;
            spacing: 15px;
            HorizontalLayout {
                spacing: 10px;
                search-box := LineEdit {
                    horizontal-stretch: 0;
                    placeholder-text: "在找什么部门呢";
                }

                Button {
                    text: "搜索";
                    width: self.preferred-width;
                    clicked => {
                        debug("search: " + search-box.text);
                        SearchPageBridge.filter-department(search-box.text);
                    }
                }
            }

            StandardListView {
                model: SearchPageBridge.department;
                current-item-changed(idx) => {
                    debug("current item changed: " + idx);
                    SearchPageBridge.load-department-events(idx);
                }
            }
        }

        ScrollView {
            EventCardGroup {
                model: SearchPageBridge.event-model;
                item-clicked(event-struct) => {
                    debug("id: " + event-struct.id + " title: " + event-struct.summary);
                    // TODO: navigate to detail page
                }
            }
        }
    }
}
