import { Token } from "../../global.slint";
import { Page, Empty } from "../../components/index.slint";
import { VerticalBox, Button, Switch, ListView, StandardListView } from "std-widgets.slint";
import { KeyBoard } from "../../modules/surrealism-ui/src/keyboard/keyboard.slint";
export global SettingPageBridge { }
export component SettingPage inherits Page {
    // TODO: implement Setting
    //day and night change
    callback timestage();
    callback languagestage();
    VerticalBox {
        //alignment: LayoutAlignment.center;
        body := Empty {
            width: 100%;
            height: 100%;
            placeholder := Rectangle {
                width: 1145px;
                height: 977px;
                x: 2px;
                y: 1px;
                border-width: 4px;
                border-color: red;
                background: white;
                Text {
                    text: "设置\n  ";
                    x:67px;
                    y:50px;
                    font-size: 20px;
                }               
    Rectangle {
        width: 90%;
        height: 156px;
        x:40px;
        y:100px;
        background:Token.color.surface-container-high;
        border-radius:10px;
        Text {
            text: "夜间模式";
            x:25px;
            y:5px;
            font-size: 15px;
        }
        
     StandardListView {
        width: 150px;
        height: 156px;
        x:20px;
        y:25px;
        model: [ { text: "深色",}, { text: "浅色" }, { text: "跟随系统" }];
       current-item-changed => {
        root.timestage();
       }
     } 
} 
    Rectangle {
        width: 90%;
        height: 156px;
        x:40px;
        y:300px;
        background:Token.color.surface-container-high;
        border-radius: 10px;
        Text {
            x:25px;
            y:5px;
            text: "语言";
            font-size: 15px;
            StandardListView {
                x:-15px;
                y:20px;
                width: 150px;
                height: 150px;
                model: [ { text: "中文"}, { text: "English" }];
                current-item-changed => {
                    root.languagestage();
                }
             } 
      }
    }         
    Rectangle {
        width: 90%;
        height: 4%;
        background: Token.color.surface-container-high;
        x:40px;
        y:500px;
        border-radius: 10px;
        Switch {
            accessible-role: AccessibleRole.none;
            x: 14px;
            y: 8px;
            width: 132px;
            text: "活动开始提醒";
        }
    }
    Rectangle {
        width: 90%;
        height: 4%;
        background: Token.color.surface-container-high;
        x:40px;
        y:550px;
        border-radius: 10px;
        Switch {
            accessible-role: AccessibleRole.none;
            x: 14px;
            y: 8px;
            width: 132px;
            text: "活动评价提醒";
        }
    }
            }
        }
    }
    //

    // optional
    background := Empty { }

}
    //Button {
    //                     visible: true;
    //                     width: 84px;
    //                     height: 52px;
    //                     text: "Night";
    //                     x: 262px;
    //                     y: 170px;
    //                     clicked => {
    //                         Token.is-darkmode
    //                     }
    //                 }
    //                 Rectangle {
    //                     background: #0c0c0c;
    //                     width: 90px;
    //                     height: 56px;
    //                     x:20px;
    //                     y:170px;
    //                     border-color: #967070dd;
    //                     border-radius: 10px;
    //                     Text {
    //                     x: -20px;
    //                     y: 2px;
    //                     width: 128px;
    //                     height: 48px;
    //                     horizontal-alignment: TextHorizontalAlignment.center;
    //                     text: "日夜切换";
    //                     color: #ffffff;
    //                     vertical-alignment: TextVerticalAlignment.center;
                        
    //                 }
    
    //  Rectangle { min-width: 16px; min-height: 16px; /* @lsp:ignore-node */ }}
    //                 Button {
    //                     visible: true;
    //                     x: 176px;
    //                     y: 170px;
    //                     width: 84px;
    //                     height: 52px;
    //                     text: "Day";
    //                 }
    //                 Text {
    //                     text: "设置背景颜色";
    //                     x:20px;
    //                     y:300px;
    //                     width: 90px;
    //                     height: 56px;
    //                     horizontal-alignment: TextHorizontalAlignment.center;
    //                     vertical-alignment: TextVerticalAlignment.center;
    //                 }
    // Switch {
        //     width: 200px;
        //     height: 50px;
        //     x:25px;
        //     y:33px;
        //     text: "深色";
            
        // }
        // Switch {
        //     width: 200px;
        //     height: 50px;
        //     x:25px;
        //     y:66px;
        //     text: "跟随系统";
        //     checked: true;
        // }
        // Switch {
        //     width: 200px;
        //     height: 50px;
        //     x:25px;
        //     y:99px;
        //     text: "浅色";
            
        // }
        //Switch {
            //     width: 200px;
            //     height: 50px;
            //     text: "中文";
            //     x:0px;
            //     y:20px;
            // }
            // Switch {
            //     width: 200px;
            //     height: 50px;
            //     text: "English";
            //     x:0px;
            //     y:70px;
            // }