import { SText, SButton } from "../modules/surrealism-ui/index.slint";
import { Token } from "../global.slint";

export component MainView {
    callback startLink <=> link-button.clicked;
    in-out property <string> version-string <=> version-label.text;
    evento-image := Image {
        height: 240px;
        width: 700px;
        source: Token.image.display.evento;
    }

    link-button := SButton {
        width: 400px;
        height: 80px;
        y: evento-image.y + evento-image.height + 140px;
        text: "使用Link登录";
        font-size: 35px;
        theme: Dark;
        border-radius: 12px;
        show-icon: true;
        icon: Token.image.icon.sast-link;
    }

    visitor-button := SButton {
        y: link-button.y + link-button.height + 30px;
        text: "访客登录";
        theme: Light;
        border-radius: 8px;
        show-icon: true;
        icon: @image-url("../modules/surrealism-ui/icons/user.svg");
    }

    group-label := SText {
        y: visitor-button.y + visitor-button.height + 20px;
        text: "SAST-C++组开发";
        theme: Token.surrealism-ui-default-theme;
    }

    version-label := SText {
        y: group-label.y + group-label.height + 5px;
        theme: Token.surrealism-ui-default-theme;
    }
}
