export global AccountManagerBridge {
    in-out property <bool> is-login;
    in-out property <bool> loading: false;
    callback request-login();
    callback request-logout();
}

export global AccountManager {
    out property <bool> is-login: AccountManagerBridge.is-login;
    public function request-login() {
        AccountManagerBridge.request-login();
    }
    public function request-logout() {
        AccountManagerBridge.request-logout();
    }
}
