import { Button, Palette } from "std-widgets.slint";
import { Token } from "../global.slint";

// This file should not be imported, only used to select color

component test {
    in property background <=> c.background;
    in property text <=> t.text;
    HorizontalLayout {
        c := Rectangle {
            height: 50px;
            width: 100px;
            background: Palette.foreground;
        }

        t := Text {
            color: Token.color.on-surface;
            text: "Palette.foreground";
        }
    }
}

component ColorViewer inherits Window {
    background: Token.color.surface;
    Button {
        y: - self.height;
        text: Token.is-darkmode ? "darkmode" : "lightmode";
        clicked => {
            Token.switch-display-mode();
        }
    }

    body := HorizontalLayout {
        VerticalLayout {
            test {
                background: Token.color.primary-container;
                text: "Token.color.primary-container";
            }

            test {
                background: Token.color.on-primary-container;
                text: "Token.color.on-primary-container";
            }

            test {
                background: Token.color.surface;
                text: "Token.color.surface";
            }

            test {
                background: Token.color.on-surface;
                text: "Token.color.on-surface";
            }

            test {
                background: Token.color.surface-variant;
                text: "Token.color.surface-variant";
            }

            test {
                background: Token.color.on-surface-variant;
                text: "Token.color.on-surface-variant";
            }

            test {
                background: Token.color.inverse-surface;
                text: "Token.color.inverse-surface";
            }

            test {
                background: Token.color.inverse-on-surface;
                text: "Token.color.inverse-on-surface";
            }

            test {
                background: Token.color.outline;
                text: "Token.color.outline";
            }

            test {
                background: Token.color.outline-variant;
                text: "Token.color.outline-variant";
            }

            test {
                background: #3a3a3a;
                text: "#3a3a3a";
            }

            test {
                background: #F5F5F5;
                text: "#F5F5F5 ";
            }
        }
    }
}
