export enum MessageType{
    Info,
    Warning,
    Error
}

export global MessageManagerBridge {
    in-out property <string> content: "Test content";
    in-out property <bool> visible;
    in-out property <MessageType> type;
    callback show-message(string, MessageType);
}

export global MessageManager {
    out property <string> content: MessageManagerBridge.content;
    out property <bool> visible: MessageManagerBridge.visible;
    out property <MessageType> type: MessageManagerBridge.type;
    public function show-message(content: string, type: MessageType) {
        MessageManagerBridge.show-message(content, type);
    }
}
