export enum ViewName{
    DiscoveryPage,
    SearchPage,
    HistoryPage,
    MyEventPage,
    DetailPage,
    AboutPage,
    SettingPage,
    LoginOverlay,
    MenuOverlay,
}

export global ViewManagerBridge {
    // nav request
    callback navigate-to(ViewName);
    callback clean-navigate-to(ViewName);
    callback replace-navigate-to(ViewName);
    callback prior-view();
    // control view visibility
    pure callback is-show(ViewName) -> bool;
    in-out property <bool> refresh;
}

export global ViewManager {
    // nav request
    public function navigate-to(view: ViewName) {
        ViewManagerBridge.navigate-to(view);
    }
    public function clean-navigate-to(view: ViewName) {
        ViewManagerBridge.clean-navigate-to(view);
    }
    public function replace-navigate-to(view: ViewName) {
        ViewManagerBridge.replace-navigate-to(view);
    }
    public function prior-view() {
        ViewManagerBridge.prior-view();
    }
    // control view visibility
    public pure function is-show(view: ViewName) -> bool {
        return ViewManagerBridge.is-show(view);
    }
}
