import { Token } from "../../global.slint";
import { Overlay, Empty } from "../../components/index.slint";

import { SButton } from "../../modules/surrealism-ui/index.slint";

export global LoginOverlayBridge {
    in-out property <string> version:"v0.0.0-00000000";
    callback link-login();
    callback guest-login();
}

component LoginContent inherits Rectangle {
    clip: true;
    background: Token.color.surface;
    border-radius: 18px;
    border-width: 3px;
    border-color: Token.color.outline;
    height: 550px;
    width: 360px;
    background := Image {
        x: 0;
        y: layout-logo.absolute-position.y - root.absolute-position.y;
        width: 100%;
        height: 96%;
        z: -1;
        source: Token.image.display.evento-bg;
        image-fit: cover;
    }

    // workaround applied: empty layout and separate elements
        // for precise layout
        layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        padding: 16px;
        layout-logo := Rectangle {
            vertical-stretch: 0.68;
            border-width: 2px;
            border-color: red;
        }

        layout-login-button := Rectangle {
            vertical-stretch: (1 - layout-logo.vertical-stretch) / 2;
            border-width: 2px;
            border-color: red;
        }

        VerticalLayout {
            vertical-stretch: (1 - layout-logo.vertical-stretch) / 2;
            layout-guest-button := Rectangle {
                vertical-stretch: 0.4;
                border-width: 2px;
                border-color: green;
            }

            Rectangle {
                vertical-stretch: 0.25;
            }

            HorizontalLayout {
                vertical-stretch: 0.35;
                layout-developer-label := Rectangle {
                    border-width: 2px;
                    border-color: red;
                }

                layout-version-label := Rectangle {
                    vertical-stretch: 0;
                    border-width: 2px;
                    border-color: red;
                }
            }
        }
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        logo := Empty {
            x: layout-logo.absolute-position.x - root.absolute-position.x;
            y: layout-logo.absolute-position.y - root.absolute-position.y;
            width: layout-logo.width;
            height: layout-logo.height;
            Image {
                vertical-stretch: 2;
                // min-height: 0px;
                    // width: 300px;
                    height: 90px;
                image-fit: contain;
                source: Token.image.display.evento;
            }
        }

        login-button := Empty {
            x: layout-login-button.absolute-position.x - root.absolute-position.x;
            y: layout-login-button.absolute-position.y - root.absolute-position.y;
            width: layout-login-button.width;
            height: layout-login-button.height;
            SButton {
                width: 240px;
                height: 55px;
                // to hide default text
                    text: "";
                // invert color
                    theme: Token.is-darkmode ? Light : Dark;
                background: Token.color.inverse-surface;
                border-width: 0;
                border-radius: 4px;
                clicked => {
                    LoginOverlayBridge.link-login();
                }
                HorizontalLayout {
                    padding: 8px;
                    spacing: 0;
                    Rectangle {
                        horizontal-stretch: 2;
                        Image {
                            height: 32px;
                            source: Token.image.icon.sast-link;
                        }
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                        Text {
                            text: "使用 Link 登录";
                            font-size: Token.font.headline.small.size;
                            font-weight: Token.font.headline.small.weight;
                            color: Token.color.inverse-on-surface;
                        }
                    }
                }
            }
        }

        guest-button := Empty {
            x: layout-guest-button.absolute-position.x - root.absolute-position.x;
            y: layout-guest-button.absolute-position.y - root.absolute-position.y;
            width: layout-guest-button.width;
            height: layout-guest-button.height;
            Rectangle {
                width: 100px;
                guest-button-area := TouchArea {
                    mouse-cursor: MouseCursor.pointer;
                    clicked => {
                        LoginOverlayBridge.guest-login();
                    }
                }

                HorizontalLayout {
                    Image {
                        horizontal-stretch: 1;
                        height: 30px;
                        source: Token.image.icon.account-box-outline;
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                        Text {
                            text: "访客登录";
                            font-size: Token.font.body.large.size;
                        }

                        // underline
                            Text {
                            visible: guest-button-area.has-hover;
                            text: "_________";
                            font-size: Token.font.body.large.size;
                            font-weight: Token.font.body.large.weight;
                        }
                    }
                }
            }
        }

        developer-label := Empty {
            x: layout-developer-label.absolute-position.x - root.absolute-position.x;
            y: layout-developer-label.absolute-position.y - root.absolute-position.y;
            width: layout-developer-label.width;
            height: layout-developer-label.height;
            Text {
                text: "SAST-C++组开发";
                font-size: Token.font.label.large.size;
                font-weight: Token.font.label.large.weight;
                color: Token.color.on-surface;
            }
        }

        version-label := Empty {
            x: layout-version-label.absolute-position.x - root.absolute-position.x;
            y: layout-version-label.absolute-position.y - root.absolute-position.y;
            width: layout-version-label.width;
            height: layout-version-label.height;
            Text {
                text: LoginOverlayBridge.version;
                font-size: Token.font.label.large.size;
                font-weight: Token.font.label.large.weight;
                color: Token.color.on-surface;
            }
        }
    }
}

export component LoginOverlay inherits Overlay {
    content := LoginContent { }
}
