import { Token } from "../../global.slint";
import { Overlay, Empty } from "../../components/index.slint";

export global MenuOverlayBridge { }

export component MenuOverlay inherits Overlay {
    // TODO: implement Menu
    // optional
    background := Empty { }

    layout := VerticalLayout {
        visible: false;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
    }

    body := Empty {
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        placeholder := Rectangle {
            border-width: 4px;
            border-color: red;
            Text {
                text: "菜单\n  （需要暗色背景，详见设计稿）";
            }
        }
    }
}
