import { EventoImageToken } from "./assets/index.slint";
import { MdStyleToken } from "./logic/md_style_token.slint";

import { Palette } from "std-widgets.slint";

export { 
    MdFontData,
    MdElevationData,
} from "./logic/md_style_token.slint";

export global Token {
    out property is-darkmode <=> MdStyleToken.is-darkmode;
    out property image <=> EventoImageToken.image;
    out property font <=> MdStyleToken.font;
    out property color <=> MdStyleToken.color;
    out property elevation <=> MdStyleToken.elevation;
    public function set-display-mode(color-scheme: ColorScheme) {
        if (color-scheme == ColorScheme.unknown) {
            return;
        }
        Palette.color-scheme = color-scheme;
    }
    public function switch-display-mode() {
        Palette.color-scheme = Palette.color-scheme == ColorScheme.light ? ColorScheme.dark : ColorScheme.light;
    }
}
